/* testcls.c generated by valac 0.16.0, the Vala compiler
 * generated from testcls.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_ADRESS (adress_get_type ())
#define ADRESS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ADRESS, Adress))
#define ADRESS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ADRESS, AdressClass))
#define IS_ADRESS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ADRESS))
#define IS_ADRESS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ADRESS))
#define ADRESS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ADRESS, AdressClass))

typedef struct _Adress Adress;
typedef struct _AdressClass AdressClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Adress {
	GObject parent_instance;
	gchar* _street;
	gchar* _housenr;
};

struct _AdressClass {
	GObjectClass parent_class;
};

static gpointer adress_parent_class = NULL;

GType adress_get_type (void) G_GNUC_CONST;
enum  {
	ADRESS_DUMMY_PROPERTY,
	ADRESS_STREET,
	ADRESS_HOUSENR
};
Adress* adress_new (void);
Adress* adress_construct (GType object_type);
const gchar* adress_get_street (Adress* self);
void adress_set_street (Adress* self, const gchar* value);
const gchar* adress_get_housenr (Adress* self);
void adress_set_housenr (Adress* self, const gchar* value);
static void adress_finalize (GObject* obj);
static void _vala_adress_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_adress_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
gint _vala_main (void);


Adress* adress_construct (GType object_type) {
	Adress * self = NULL;
	self = (Adress*) g_object_new (object_type, NULL);
	return self;
}


Adress* adress_new (void) {
	return adress_construct (TYPE_ADRESS);
}


const gchar* adress_get_street (Adress* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_street;
	result = _tmp0_;
	return result;
}


void adress_set_street (Adress* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_street);
	self->_street = _tmp1_;
	g_object_notify ((GObject *) self, "street");
}


const gchar* adress_get_housenr (Adress* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_housenr;
	result = _tmp0_;
	return result;
}


void adress_set_housenr (Adress* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_housenr);
	self->_housenr = _tmp1_;
	g_object_notify ((GObject *) self, "housenr");
}


static void adress_class_init (AdressClass * klass) {
	adress_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_adress_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_adress_set_property;
	G_OBJECT_CLASS (klass)->finalize = adress_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADRESS_STREET, g_param_spec_string ("street", "street", "street", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ADRESS_HOUSENR, g_param_spec_string ("housenr", "housenr", "housenr", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void adress_instance_init (Adress * self) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	_tmp0_ = g_strdup ("");
	self->_street = _tmp0_;
	_tmp1_ = g_strdup ("");
	self->_housenr = _tmp1_;
}

static void adress_finalize (GObject* obj) {
	Adress * self;
	self = ADRESS (obj);
	_g_free0 (self->_street);
	_g_free0 (self->_housenr);
	G_OBJECT_CLASS (adress_parent_class)->finalize (obj);
}


GType adress_get_type (void) {
	static volatile gsize adress_type_id__volatile = 0;
	if (g_once_init_enter (&adress_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AdressClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) adress_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Adress), 0, (GInstanceInitFunc) adress_instance_init, NULL };
		GType adress_type_id;
		adress_type_id = g_type_register_static (G_TYPE_OBJECT, "Adress", &g_define_type_info, 0);
		g_once_init_leave (&adress_type_id__volatile, adress_type_id);
	}
	return adress_type_id__volatile;
}


static void _vala_adress_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Adress * self;
	self = ADRESS (object);
	switch (property_id) {
		case ADRESS_STREET:
		g_value_set_string (value, adress_get_street (self));
		break;
		case ADRESS_HOUSENR:
		g_value_set_string (value, adress_get_housenr (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_adress_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Adress * self;
	self = ADRESS (object);
	switch (property_id) {
		case ADRESS_STREET:
		adress_set_street (self, g_value_get_string (value));
		break;
		case ADRESS_HOUSENR:
		adress_set_housenr (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


gint _vala_main (void) {
	Adress* x = adress_new ();
	/* set property */
	GValue val = G_VALUE_INIT;
	g_value_init (&val, G_TYPE_STRING);
	g_value_set_string (&val, "hello");
	g_object_set_property(G_OBJECT (x), "street", &val);
	/* printf */
	g_printf("%s\n", x->_street);
	_g_object_unref0 (x);//_adress_unref0 (x);
	return 0;
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	return _vala_main ();
}



